# Generated by Django 5.1 on 2024-08-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shikoyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telnomer', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('company', models.CharField(choices=[('MARS', 'MARS'), ('Uzinfacom', 'Uzinfacom'), ('Realsoft', 'Realsoft'), ('Smartsoft', 'Smartsoft'), ('Cloudit', 'Cloudit'), ('Pentagon', 'Pentagon'), ('UIC group', 'UIC group'), ('Cometa', 'Cometa'), ('MXX', 'MXX'), ('YPX', 'YPX')], max_length=1000000000000)),
                ('complaint', models.TextField()),
                ('status', models.CharField(choices=[('Bajarildi', 'Bajarildi'), ('Bajarilmoqda', 'Bajarilmoqda'), ('Bajarilmadi', 'Bajarilmadi')], max_length=50)),
            ],
        ),
    ]
